# Generated by Django 3.1.5 on 2021-01-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contact',
        ),
        migrations.DeleteModel(
            name='ActivityStatus',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='ContactSource',
        ),
        migrations.DeleteModel(
            name='ContactStatus',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
