# Generated by Django 3.1.5 on 2021-01-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_1', '0003_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
